/**
 * Referral system.
 *
 * Every user gets a unique share code. When a new user first signs in with a
 * `ref` code present (captured into a cookie by middleware), they are attributed
 * to that referrer — once, permanently. Thereafter the referrer earns the
 * "referral" third of the rake generated by that player's pot contributions,
 * credited to a claimable referral-earnings balance (see the ledger). The player
 * claims those earnings into their withdrawable available balance.
 */

import { randomInt } from "node:crypto";
import type { Asset } from "@prisma/client";
import { prisma } from "@/lib/db/prisma";
import { isTokenConfigured } from "@/lib/env";

// Unambiguous alphabet (no 0/O/1/I) for hand-shareable codes.
const CODE_ALPHABET = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
const CODE_LENGTH = 7;

function randomCode(): string {
  let out = "";
  for (let i = 0; i < CODE_LENGTH; i++) {
    out += CODE_ALPHABET[randomInt(CODE_ALPHABET.length)];
  }
  return out;
}

/** Assign a unique referral code to a user if they don't have one yet. */
export async function ensureReferralCode(userId: string): Promise<string> {
  const existing = await prisma.user.findUnique({
    where: { id: userId },
    select: { referralCode: true },
  });
  if (existing?.referralCode) return existing.referralCode;

  for (let attempt = 0; attempt < 6; attempt++) {
    const code = randomCode();
    try {
      await prisma.user.update({ where: { id: userId }, data: { referralCode: code } });
      return code;
    } catch {
      // Unique collision — retry with a new code.
    }
  }
  throw new Error("Could not allocate a referral code");
}

/**
 * Attribute a newly-created user to a referrer by code. No-op if the user is
 * already attributed, the code is unknown, or it resolves to the user themselves.
 */
export async function attributeReferral(
  userId: string,
  refCode: string,
): Promise<boolean> {
  const code = refCode.trim().toUpperCase();
  if (!code) return false;

  const user = await prisma.user.findUnique({
    where: { id: userId },
    select: { referredById: true },
  });
  if (!user || user.referredById) return false; // already attributed

  const referrer = await prisma.user.findUnique({
    where: { referralCode: code },
    select: { id: true },
  });
  if (!referrer || referrer.id === userId) return false;

  await prisma.user.update({
    where: { id: userId },
    data: { referredById: referrer.id, referredAt: new Date() },
  });
  return true;
}

export interface ReferralAssetBalance {
  asset: Asset;
  claimable: string; // base units
  totalEarned: string; // base units, lifetime
}

export interface ReferralSummary {
  code: string;
  refereeCount: number;
  balances: ReferralAssetBalance[];
}

const TRACKED_ASSETS: Asset[] = isTokenConfigured()
  ? ["SOL", "USDC", "TOKEN"]
  : ["SOL", "USDC"];

/** Everything the profile referral panel needs. */
export async function getReferralSummary(userId: string): Promise<ReferralSummary> {
  const code = await ensureReferralCode(userId);

  const [refereeCount, balances, earnedEntries] = await Promise.all([
    prisma.user.count({ where: { referredById: userId } }),
    prisma.balance.findMany({ where: { userId } }),
    prisma.ledgerEntry.groupBy({
      by: ["asset"],
      where: { userId, accountType: "USER_REFERRAL_EARNINGS", direction: "CREDIT" },
      _sum: { amount: true },
    }),
  ]);

  const claimableByAsset = new Map(
    balances.map((b) => [b.asset, b.referralEarningsAmount]),
  );
  const earnedByAsset = new Map(
    earnedEntries.map((e) => [e.asset, e._sum.amount ?? 0n]),
  );

  const assetBalances: ReferralAssetBalance[] = TRACKED_ASSETS.map((asset) => ({
    asset,
    claimable: (claimableByAsset.get(asset) ?? 0n).toString(),
    totalEarned: (earnedByAsset.get(asset) ?? 0n).toString(),
  }));

  return { code, refereeCount, balances: assetBalances };
}
